# Generated by Django 4.2 on 2023-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('companion', models.CharField(max_length=250)),
                ('event_type', models.CharField(choices=[('C', 'Concert'), ('S', 'Sport')], default='C', max_length=1)),
            ],
        ),
    ]
