# Generated by Django 4.2 on 2023-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='video_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
