# Generated by Django 4.2 on 2023-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_highlight_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='content',
            field=models.TextField(verbose_name='Your Highlights'),
        ),
    ]
