# Generated by Django 4.2 on 2023-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ticket_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.artist'),
        ),
    ]
